Fix build on MacOS-X 10.14: missing Xerces include dir
This undoes most of the Xerces related part of the commits listed below.
The issue resolved here is that the Xerces include dir *is* set in the
CMakeLists.txt of src/Base, but it got removed from various App and Gui
dirs in src/Mod. If those now include a header from src/Base, which
itself includes xercesc, the build fails using Apple clang version 11.0.0
(clang-1100.0.33.17) on Mojave, configured using cmake 3.22.1, with
errors like the following:

In file included from .../src/Mod/Part/App/FeaturePartBoolean.cpp:34:
In file included from .../src/App/Application.h:33:
.../src/Base/Parameter.h:54:10: fatal error: 'xercesc/util/XercesDefs.hpp' file not found
 #include <xercesc/util/XercesDefs.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Finally, a full list of the commits that introduced this spurious include
dir optimization for reference:
- Drawing: commit 39f40b81ccbe8ca3a918ceec1bd20a9fd5be3f67
- Image: commit b90cbc964e6e0ed2fb1a27d21b4de16bc9798d4b
- Import: commit e0df029f597da12a9ec6b9a874d676c3ee0518d4
- Inspection: commit 604fdfbc88dc9652ece60c09209fe512e0304ba1
- Mesh: commit 25295aadcbd183e5149f9d8ea606a862a90c40a4
- Part: commit f44b9970bc37025044263cce47b76189d4b628a9
- PartDesign: commit a7886b808e8e5fba425b0a5c901658c84ac277e0
- Path: commit 60b9f66d4d93d799c9438bfc5b3849bb79d49e97
- Points: commit fee7823c7d54e5ca78d22ca3bd3b3783f795ccda
- Raytracing: commit 7aa7241509ec1fb9329404303bfd1d2446a93db7
- ReverseEnginering: commit c5edd4cd36ba8eaecb0d139f6b69b7c138ce34e2
- Robot: commit ba512bf62b41598a517ac446edd1c153f75aae60
- Sketcher: commit 4804d56e6167aecaa294c8ba2ec19d7b88afae6f
- Spreadsheet: commit 5142f4a687729e156d83c61a0165cdeb6874e8d
- Start: commit 0b05a4f05ea35c7131a80b41b1975353114204d7
- Surface: commit ed9a90f24aac0f8a7ffa98a446b006dab9da95f9
- TechDraw: commit 8b65ded8a51110ca40050025bcf15b3cf7b0c078
- Test: commit 3b9e782acf7ad4c2bb0cec3aabe3b6efeb3253ef
- Web: commit f0b58c2968f0621b03bd55a61e94a212b1df5d8e